const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{"8Direction": 0},
	{Player: 0},
	{Solid: 0},
	{wall: 0},
	{Sine: 0},
	{Dino: 0},
	{Coin: 0},
	{Judul: 0},
	{Tween: 0},
	{Play: 0},
	{Win: 0},
	{Lose: 0},
	{Retry: 0},
	{quiz: 0},
	{Text: 0},
	{Text2: 0},
	{Dino2: 0},
	{Player2: 0},
	{Text3: 0},
	{joystick: 0},
	{dist: 0},
	{joystickKecil: 0},
	{DragDrop: 0},
	{drag: 0},
	{Touch: 0},
	{Audio: 0},
	{Dino3: 0},
	{info: 0},
	{Text4: 0},
	{score: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	Dino: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Judul: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Win: class extends self.ISpriteInstance {},
	Lose: class extends self.ISpriteInstance {},
	Retry: class extends self.ISpriteInstance {},
	quiz: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Dino2: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	joystick: class extends self.ISpriteInstance {},
	joystickKecil: class extends self.ISpriteInstance {},
	drag: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Dino3: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {}
}